### ISSUE TITLE
The weight of meta_net does not change

### ISSUE THREAD

**Issue by okazakikyou** [renzhenwang/bias-adaptive-classifier#2]
I observed the results of every ten iterations and found that the weights of the two linear layers of meta_net did not change. I have been confused by this result and how the bi-level update is achieved.

**Comment by renzhenwang** [comment]
Hi, we checked the question and found that the weights of meta_net are updated normally, by Inserting the following scripts at Line 311 in train_fix_l2ac.py:
![code](https://github.com/renzhenwang/bias-adaptive-classifier/assets/46158457/4db3cc5c-148d-48e6-a503-aac116f14378)
Thanks for your attention!

**Comment by okazakikyou** [comment]
Thank you for your response that helped me solve my problem. And this is a very excellent paper.
