### ISSUE TITLE
Cannot reproduce performances on CIFAR-10

### ISSUE THREAD

**Issue by machengcheng2016** [renzhenwang/bias-adaptive-classifier#4]
Greetings,
Sorry to bother again. I was running experiments on CIFAR-10 with $\gamma_l=100$ and $\gamma_u=-100$, keeping all hyper-parameters unchanged, however I only got 75.72% bACC (it is the best bACC along whole training process), instead of 82.2% as reported in Table 1.

Besides, I also tried to change [Line 274](https://github.com/renzhenwang/bias-adaptive-classifier/blob/main/train_fix_l2ac.py#L274) from `if args.imb_ratio_l == args.imb_ratio_u:` to `if True:`, since I suspect that the logit adjustment may also be needed when $\gamma_l \neq \gamma_u$ (as we have discussed [here](https://github.com/renzhenwang/bias-adaptive-classifier/issues/3)). However, the best bACC is still ~76%, still far away from 82.2% in Table 1. 
Is there anything I've missed or misunderstanded?

**Comment by renzhenwang** [comment]
> Greetings, Sorry to bother again. I was running experiments on CIFAR-10 with γl=100 and γu=−100, keeping all hyper-parameters unchanged, however I only got 75.72% bACC (it is the best bACC along whole training process), instead of 82.2% as reported in Table 1.
> 
> Besides, I also tried to change [Line 274](https://github.com/renzhenwang/bias-adaptive-classifier/blob/main/train_fix_l2ac.py#L274) from `if args.imb_ratio_l == args.imb_ratio_u:` to `if True:`, since I suspect that the logit adjustment may also be needed when γl≠γu (as we have discussed [here](https://github.com/renzhenwang/bias-adaptive-classifier/issues/3)). However, the best bACC is still ~76%, still far away from 82.2% in Table 1. Is there anything I've missed or misunderstanded?

Hi, Chengcheng! Is your running script `python train_fix_l2ac.py --gpu 0 --ratio 2 --num_max 1500 --imb_ratio_l 100 --imb_ratio_u 100 --reverse True  --epoch 500 --val-iteration 500 --out result/cifar10@N_1500_r_100_reverse_fix_l2ac --dataset cifar10 --workers 0` as in run.sh?

**Comment by machengcheng2016** [comment]
Yeah, I think so. 
After a careful check yesterday, the only thing I've changed to this whole repo is to exclude the `train_labeled_idxs` from `train_unlabeled_idxs` ([here](https://github.com/renzhenwang/bias-adaptive-classifier/blob/main/dataset/fix_cifar10.py#L68C78-L68C78)), just to be consistent with all previous SOTA baselines like [DASO](https://github.com/ytaek-oh/daso/blob/main/lib/dataset/utils.py#L91), [ABC](https://github.com/LeeHyuck/ABC/blob/main/ABCcode0920/dataset/fix_cifar10.py#L67), and [USB](https://github.com/microsoft/Semi-supervised-learning/blob/main/config/classic_cv_imb/fixmatch/fixmatch_cifar10_lb1500_100_ulb3000_100_0.yaml#L46).
Seems such a tiny setting can make a big difference to the final performance :worried:

**Comment by renzhenwang** [comment]
> Yeah, I think so. After a careful check yesterday, the only thing I've changed to this whole repo is to exclude the `train_labeled_idxs` from `train_unlabeled_idxs` ([here](https://github.com/renzhenwang/bias-adaptive-classifier/blob/main/dataset/fix_cifar10.py#L68C78-L68C78)), just to be consistent with all previous SOTA baselines like [DASO](https://github.com/ytaek-oh/daso/blob/main/lib/dataset/utils.py#L91), [ABC](https://github.com/LeeHyuck/ABC/blob/main/ABCcode0920/dataset/fix_cifar10.py#L67), and [USB](https://github.com/microsoft/Semi-supervised-learning/blob/main/config/classic_cv_imb/fixmatch/fixmatch_cifar10_lb1500_100_ulb3000_100_0.yaml#L46). Seems such a tiny setting can make a big difference to the final performance 😟

We have run the code and the result has been successfully reproduced as follows:
![result](https://github.com/renzhenwang/bias-adaptive-classifier/assets/46158457/61acf332-970d-49e8-941f-2d46f9a8f03a)

**Comment by machengcheng2016** [comment]
Yes, I totally agree. If including train_labeled_idxs into train_unlabeled_idxs, I can also get 83.32% bACC, even higher than that reported in Table 1. 
![image](https://github.com/renzhenwang/bias-adaptive-classifier/assets/22851860/23632e97-624b-4a59-a66c-b3ce242c7db5)

But if keeping the same experimental setting with previous SOTA methods (see the hyperlinks I mentioned above) that excluding train_labeled_idxs from train_unlabeled_idxs, the bACC drops to ~76%, which really surprises me.
![image](https://github.com/renzhenwang/bias-adaptive-classifier/assets/22851860/43bca4c6-23f1-443f-be22-66885f16b449)

**Comment by machengcheng2016** [comment]
I think my issue has been addressed, because it is all about whether taking labeled data as a part of unlabeled set. 😄
